Added support for Starname chain
ovrclk/cosmos-omnibus pull request #65
Opened 2021-11-25 07:16 UTC by betterclever

Draft PR for Starname support

Was not able to find a seed list anywhere. Could only find a list of peers on their official repo here: https://github.com/iov-one/starnamed

Created a PR in the Chain Registry to update the chain.json here: https://github.com/cosmos/chain-registry/pull/70

The chain starts but is perpertually syncing up blocks from peers from what I understand, trying to contact with the startname team to find more info from them.

2021-11-29 18:16 UTC, tombeynon requested changes
Couple typos for `start` instead of `star` but otherwise looks good

2021-11-30 04:01 UTC, betterclever commented
my bad, updating the PR rebased on current master.

2021-12-02 18:49 UTC, betterclever commented
Updated the PR with the typo fixes + changing chain.json from Chain Registry

2021-12-06 16:53 UTC, tombeynon approved these changes

2021-12-06 17:00 UTC, merged